# Generated by Django 5.2.18 on 2026-10-09 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KreditProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=160)),
                ('subtitle_az', models.CharField(max_length=160, null=True)),
                ('subtitle_ru', models.CharField(max_length=160, null=True)),
                ('subtitle_en', models.CharField(max_length=160, null=True)),
                ('chip', models.CharField(max_length=20)),
                ('chip_az', models.CharField(max_length=20, null=True)),
                ('chip_ru', models.CharField(max_length=20, null=True)),
                ('chip_en', models.CharField(max_length=20, null=True)),
                ('chip_icon', models.CharField(max_length=20)),
                ('price_label', models.CharField(blank=True, help_text='e.g. "2 ₼"; optional', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('options', models.JSONField(blank=True, default=list, help_text='Selectable amounts, if any')),
                ('amount_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('validity_days', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_debts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
