# Generated by Django 5.2.18 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kredit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kreditproduct',
            name='chip_ru',
        ),
        migrations.RemoveField(
            model_name='kreditproduct',
            name='subtitle_ru',
        ),
    ]
