# Generated by Django 5.2.18 on 2026-10-09 11:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=160)),
                ('title_az', models.CharField(max_length=160, null=True)),
                ('title_ru', models.CharField(max_length=160, null=True)),
                ('title_en', models.CharField(max_length=160, null=True)),
                ('body', models.TextField()),
                ('body_az', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
