# Generated by Django 5.2.18 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralstep',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='referralstep',
            name='title_ru',
        ),
    ]
