# Generated by Django 5.2.18 on 2026-10-09 11:17

import api.tariffs.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('title_az', models.CharField(max_length=60, null=True)),
                ('title_ru', models.CharField(max_length=60, null=True)),
                ('title_en', models.CharField(max_length=60, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('text', models.CharField(max_length=160)),
                ('text_az', models.CharField(max_length=160, null=True)),
                ('text_ru', models.CharField(max_length=160, null=True)),
                ('text_en', models.CharField(max_length=160, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('heading', models.CharField(max_length=120)),
                ('heading_az', models.CharField(max_length=120, null=True)),
                ('heading_ru', models.CharField(max_length=120, null=True)),
                ('heading_en', models.CharField(max_length=120, null=True)),
                ('tone', models.CharField(choices=[('secondary', 'Secondary'), ('red', 'Red')], default='secondary', max_length=12)),
                ('rows', models.JSONField(default=list, help_text='[{"label", "price"}]')),
                ('rows_az', models.JSONField(default=list, help_text='[{"label", "price"}]', null=True)),
                ('rows_ru', models.JSONField(default=list, help_text='[{"label", "price"}]', null=True)),
                ('rows_en', models.JSONField(default=list, help_text='[{"label", "price"}]', null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedesignSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('label_az', models.CharField(max_length=60, null=True)),
                ('label_ru', models.CharField(max_length=60, null=True)),
                ('label_en', models.CharField(max_length=60, null=True)),
                ('minimum', models.PositiveSmallIntegerField()),
                ('maximum', models.PositiveSmallIntegerField()),
                ('step', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TariffFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('name_az', models.CharField(max_length=60, null=True)),
                ('name_ru', models.CharField(max_length=60, null=True)),
                ('name_en', models.CharField(max_length=60, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=160)),
                ('subtitle_az', models.CharField(blank=True, max_length=160, null=True)),
                ('subtitle_ru', models.CharField(blank=True, max_length=160, null=True)),
                ('subtitle_en', models.CharField(blank=True, max_length=160, null=True)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'tariff families',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(default='istesen', max_length=40)),
                ('title', models.CharField(default='IsteSen', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('19.10'), max_digits=8)),
                ('validity_days', models.PositiveSmallIntegerField(default=30)),
                ('activated_at', models.DateTimeField()),
                ('last_payment_at', models.DateTimeField()),
                ('next_payment_at', models.DateTimeField()),
                ('data_remaining_gb', models.DecimalField(decimal_places=2, default=Decimal('7.20'), max_digits=6)),
                ('data_total_gb', models.PositiveSmallIntegerField(default=16)),
                ('messaging_remaining_mb', models.PositiveIntegerField(default=1003)),
                ('messaging_total_gb', models.PositiveSmallIntegerField(default=1)),
                ('minutes_remaining', models.PositiveIntegerField(default=30)),
                ('minutes_total', models.PositiveIntegerField(default=30)),
                ('redesign', models.JSONField(default=api.tariffs.models.default_redesign)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tariff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('title_az', models.CharField(max_length=60, null=True)),
                ('title_ru', models.CharField(max_length=60, null=True)),
                ('title_en', models.CharField(max_length=60, null=True)),
                ('price', models.CharField(help_text='A price or a range, e.g. "12-30"', max_length=20)),
                ('period', models.CharField(max_length=40)),
                ('period_az', models.CharField(max_length=40, null=True)),
                ('period_ru', models.CharField(max_length=40, null=True)),
                ('period_en', models.CharField(max_length=40, null=True)),
                ('tagline', models.CharField(max_length=160)),
                ('tagline_az', models.CharField(max_length=160, null=True)),
                ('tagline_ru', models.CharField(max_length=160, null=True)),
                ('tagline_en', models.CharField(max_length=160, null=True)),
                ('is_new', models.BooleanField(default=False)),
                ('socials', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(default=list, help_text='[{"kind", "value"}]')),
                ('features_az', models.JSONField(default=list, help_text='[{"kind", "value"}]', null=True)),
                ('features_ru', models.JSONField(default=list, help_text='[{"kind", "value"}]', null=True)),
                ('features_en', models.JSONField(default=list, help_text='[{"kind", "value"}]', null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tariffs.changegroup')),
                ('family', models.ForeignKey(blank=True, help_text='Set when the card opens a catalogue page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_cards', to='tariffs.tarifffamily')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('title_az', models.CharField(max_length=60, null=True)),
                ('title_ru', models.CharField(max_length=60, null=True)),
                ('title_en', models.CharField(max_length=60, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('hot', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False, help_text='Selected when no ?plan= is given')),
                ('features', models.JSONField(default=list, help_text='[{"kind", "label", "value", "socials"?}]')),
                ('features_az', models.JSONField(default=list, help_text='[{"kind", "label", "value", "socials"?}]', null=True)),
                ('features_ru', models.JSONField(default=list, help_text='[{"kind", "label", "value", "socials"?}]', null=True)),
                ('features_en', models.JSONField(default=list, help_text='[{"kind", "label", "value", "socials"?}]', null=True)),
                ('hot_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hot_socials', models.JSONField(blank=True, default=list)),
                ('hot_features', models.JSONField(blank=True, default=list, help_text='[{"kind", "value"}]')),
                ('hot_features_az', models.JSONField(blank=True, default=list, help_text='[{"kind", "value"}]', null=True)),
                ('hot_features_ru', models.JSONField(blank=True, default=list, help_text='[{"kind", "value"}]', null=True)),
                ('hot_features_en', models.JSONField(blank=True, default=list, help_text='[{"kind", "value"}]', null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='tariffs.tarifffamily')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
