# Generated by Django 5.2.18 on 2026-10-09 12:01

from django.db import migrations, models


# Plans and price rows that already exist get their numbers here, so a database
# seeded before these fields existed works without re-seeding.
INCLUDED = {
    "digimax-5": (5 * 1024, 100, 50, 0),
    "digimax-10": (10 * 1024, 200, 100, 0),
    "digimax-25": (25 * 1024, 500, 200, 0),
    "premium-60": (60 * 1024, None, 500, 1024),
    "premium-100": (100 * 1024, None, None, 3 * 1024),
}
ROW_KEYS = ("data_mb", "minute", "sms", "intl_sms")  # the seeded order of a price group's rows


def fill_amounts(apps, schema_editor):
    plans = apps.get_model("tariffs", "TariffPlan")
    for slug, (data_mb, minutes, sms, roaming_mb) in INCLUDED.items():
        plans.objects.filter(slug=slug).update(
            data_mb=data_mb, minutes=minutes, sms=sms, roaming_mb=roaming_mb
        )
    for group in apps.get_model("tariffs", "PriceGroup").objects.all():
        for field in ("rows", "rows_en", "rows_az"):
            rows = getattr(group, field) or []
            if len(rows) == len(ROW_KEYS) and not any("key" in row for row in rows):
                setattr(group, field, [{"key": key, **row} for key, row in zip(ROW_KEYS, rows)])
        group.save()


# Cards seeded before these fields existed get their numbers here.
CARDS = {"digimax-3gb": (3 * 1024, 50, 28), "premium": (40 * 1024, 1000, 30)}


def fill_cards(apps, schema_editor):
    cards = apps.get_model("tariffs", "ChangeCard")
    for slug, (data_mb, minutes, validity_days) in CARDS.items():
        cards.objects.filter(slug=slug).update(
            data_mb=data_mb, minutes=minutes, validity_days=validity_days
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changecard',
            name='data_mb',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changecard',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changecard',
            name='validity_days',
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddField(
            model_name='subscribertariff',
            name='plan_slug',
            field=models.CharField(blank=True, help_text='Catalogue plan this tariff is, if it is one', max_length=40),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='data_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Empty = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Empty = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='roaming_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tariffplan',
            name='sms',
            field=models.PositiveIntegerField(blank=True, help_text='Empty = unlimited', null=True),
        ),
        migrations.RunPython(fill_amounts, migrations.RunPython.noop),
        migrations.RunPython(fill_cards, migrations.RunPython.noop),
    ]
