# Generated by Django 5.2.18 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_included_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changecard',
            name='features_ru',
        ),
        migrations.RemoveField(
            model_name='changecard',
            name='period_ru',
        ),
        migrations.RemoveField(
            model_name='changecard',
            name='tagline_ru',
        ),
        migrations.RemoveField(
            model_name='changecard',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='changegroup',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='premiumbenefit',
            name='text_ru',
        ),
        migrations.RemoveField(
            model_name='pricegroup',
            name='heading_ru',
        ),
        migrations.RemoveField(
            model_name='pricegroup',
            name='rows_ru',
        ),
        migrations.RemoveField(
            model_name='redesignslider',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='tarifffamily',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='tarifffamily',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='tariffplan',
            name='features_ru',
        ),
        migrations.RemoveField(
            model_name='tariffplan',
            name='hot_features_ru',
        ),
        migrations.RemoveField(
            model_name='tariffplan',
            name='title_ru',
        ),
    ]
