# Generated by Django 5.2.18 on 2026-10-09 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.CharField(help_text='File name under media/content/', max_length=120)),
                ('is_reward', models.BooleanField(default=False, help_text='Listed under reward games')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LotterySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('title_az', models.CharField(max_length=120, null=True)),
                ('title_ru', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('blocks', models.JSONField(default=list, help_text='Each item is {"kind": "p", "text", "num"?, "bold"?} or {"kind": "example", "items"}')),
                ('blocks_az', models.JSONField(default=list, help_text='Each item is {"kind": "p", "text", "num"?, "bold"?} or {"kind": "example", "items"}', null=True)),
                ('blocks_ru', models.JSONField(default=list, help_text='Each item is {"kind": "p", "text", "num"?, "bold"?} or {"kind": "example", "items"}', null=True)),
                ('blocks_en', models.JSONField(default=list, help_text='Each item is {"kind": "p", "text", "num"?, "bold"?} or {"kind": "example", "items"}', null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('label_az', models.CharField(max_length=60, null=True)),
                ('label_ru', models.CharField(max_length=60, null=True)),
                ('label_en', models.CharField(max_length=60, null=True)),
                ('deep_link', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('label_az', models.CharField(max_length=60, null=True)),
                ('label_ru', models.CharField(max_length=60, null=True)),
                ('label_en', models.CharField(max_length=60, null=True)),
                ('image', models.CharField(help_text='File name under media/content/', max_length=120)),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AppRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('placement', models.CharField(choices=[('home', 'Home'), ('products', 'Products'), ('benefits', 'Benefits'), ('partners', 'Partners')], max_length=12)),
                ('key', models.SlugField(max_length=40)),
                ('image', models.CharField(help_text='File name under media/content/', max_length=120)),
                ('alt', models.CharField(max_length=200)),
                ('alt_az', models.CharField(max_length=200, null=True)),
                ('alt_ru', models.CharField(max_length=200, null=True)),
                ('alt_en', models.CharField(max_length=200, null=True)),
                ('deep_link', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
                'unique_together': {('placement', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('app', 'App offer'), ('aztelekom', 'Aztelekom'), ('perk', 'Partner perk'), ('campaign', 'Campaign')], max_length=12)),
                ('slug', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=80)),
                ('sub', models.CharField(max_length=160)),
                ('sub_az', models.CharField(max_length=160, null=True)),
                ('sub_ru', models.CharField(max_length=160, null=True)),
                ('sub_en', models.CharField(max_length=160, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('image', models.CharField(help_text='File name under media/content/', max_length=120)),
                ('deep_link', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
                'unique_together': {('kind', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.CharField(help_text='File name under media/content/', max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('title_az', models.CharField(max_length=120, null=True)),
                ('title_ru', models.CharField(max_length=120, null=True)),
                ('title_en', models.CharField(max_length=120, null=True)),
                ('body', models.TextField()),
                ('body_az', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_label_az', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_label_ru', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_label_en', models.CharField(blank=True, max_length=60, null=True)),
                ('cta_deep_link', models.CharField(blank=True, max_length=120)),
                ('duration_ms', models.PositiveIntegerField(default=5000)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.story')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=80)),
                ('title_az', models.CharField(max_length=80, null=True)),
                ('title_ru', models.CharField(max_length=80, null=True)),
                ('title_en', models.CharField(max_length=80, null=True)),
                ('prize', models.CharField(max_length=40)),
                ('prize_az', models.CharField(max_length=40, null=True)),
                ('prize_ru', models.CharField(max_length=40, null=True)),
                ('prize_en', models.CharField(max_length=40, null=True)),
                ('participants', models.PositiveIntegerField(default=0)),
                ('ends_at', models.DateTimeField()),
                ('cta', models.CharField(max_length=80)),
                ('cta_az', models.CharField(max_length=80, null=True)),
                ('cta_ru', models.CharField(max_length=80, null=True)),
                ('cta_en', models.CharField(max_length=80, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='content.game')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('title_az', models.CharField(max_length=200, null=True)),
                ('title_ru', models.CharField(max_length=200, null=True)),
                ('title_en', models.CharField(max_length=200, null=True)),
                ('body', models.TextField()),
                ('body_az', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('cta', models.JSONField(blank=True, null=True)),
                ('cta_az', models.JSONField(blank=True, null=True)),
                ('cta_ru', models.JSONField(blank=True, null=True)),
                ('cta_en', models.JSONField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subscriber', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_key', models.CharField(max_length=40)),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subscriber', 'story_key')},
            },
        ),
    ]
