# Generated by Django 5.2.18 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='alt_ru',
        ),
        migrations.RemoveField(
            model_name='lotterysection',
            name='blocks_ru',
        ),
        migrations.RemoveField(
            model_name='lotterysection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='cta_ru',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='sub_ru',
        ),
        migrations.RemoveField(
            model_name='quickaction',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='story',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='cta_label_ru',
        ),
        migrations.RemoveField(
            model_name='storypage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='cta_ru',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='prize_ru',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='title_ru',
        ),
    ]
