# Generated by Django 5.2.18 on 2026-10-09 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('label', models.CharField(max_length=40)),
                ('label_az', models.CharField(max_length=40, null=True)),
                ('label_ru', models.CharField(max_length=40, null=True)),
                ('label_en', models.CharField(max_length=40, null=True)),
            ],
            options={
                'verbose_name_plural': 'pack categories',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoamingPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('name_az', models.CharField(max_length=40, null=True)),
                ('name_ru', models.CharField(max_length=40, null=True)),
                ('name_en', models.CharField(max_length=40, null=True)),
                ('sub', models.CharField(max_length=40)),
                ('sub_az', models.CharField(max_length=40, null=True)),
                ('sub_ru', models.CharField(max_length=40, null=True)),
                ('sub_en', models.CharField(max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('days', models.PositiveSmallIntegerField(help_text='Lifetime of an activation')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('title_az', models.CharField(max_length=60, null=True)),
                ('title_ru', models.CharField(max_length=60, null=True)),
                ('title_en', models.CharField(max_length=60, null=True)),
                ('subtitle', models.CharField(max_length=160)),
                ('subtitle_az', models.CharField(max_length=160, null=True)),
                ('subtitle_ru', models.CharField(max_length=160, null=True)),
                ('subtitle_en', models.CharField(max_length=160, null=True)),
                ('app', models.CharField(help_text='Icon key in the mobile app', max_length=20)),
                ('price_range', models.CharField(max_length=20)),
                ('special', models.BooleanField(default=False)),
                ('volume', models.CharField(max_length=40)),
                ('volume_az', models.CharField(max_length=40, null=True)),
                ('volume_ru', models.CharField(max_length=40, null=True)),
                ('volume_en', models.CharField(max_length=40, null=True)),
                ('periods', models.JSONField(default=list)),
                ('periods_az', models.JSONField(default=list, null=True)),
                ('periods_ru', models.JSONField(default=list, null=True)),
                ('periods_en', models.JSONField(default=list, null=True)),
                ('cta', models.CharField(max_length=40)),
                ('cta_az', models.CharField(max_length=40, null=True)),
                ('cta_ru', models.CharField(max_length=40, null=True)),
                ('cta_en', models.CharField(max_length=40, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('internet', 'Internet'), ('social', 'Social'), ('roaming', 'Roaming'), ('kredit', 'Kredit')], max_length=10)),
                ('pack_id', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('auto_renew', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_activations', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pack_activation', to='billing.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='InternetPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('name_az', models.CharField(max_length=40, null=True)),
                ('name_ru', models.CharField(max_length=40, null=True)),
                ('name_en', models.CharField(max_length=40, null=True)),
                ('sub', models.CharField(max_length=80)),
                ('sub_az', models.CharField(max_length=80, null=True)),
                ('sub_ru', models.CharField(max_length=80, null=True)),
                ('sub_en', models.CharField(max_length=80, null=True)),
                ('label', models.CharField(help_text='Shown on the activation and the receipt', max_length=80)),
                ('label_az', models.CharField(help_text='Shown on the activation and the receipt', max_length=80, null=True)),
                ('label_ru', models.CharField(help_text='Shown on the activation and the receipt', max_length=80, null=True)),
                ('label_en', models.CharField(help_text='Shown on the activation and the receipt', max_length=80, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('renews', models.BooleanField(default=False)),
                ('hours', models.PositiveIntegerField(help_text='Lifetime of an activation')),
                ('top_position', models.PositiveSmallIntegerField(blank=True, help_text='Position in "TOP internet packs"; empty hides it', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs', to='packs.packcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('title_az', models.CharField(max_length=40, null=True)),
                ('title_ru', models.CharField(max_length=40, null=True)),
                ('title_en', models.CharField(max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('validity', models.CharField(max_length=20)),
                ('validity_az', models.CharField(max_length=20, null=True)),
                ('validity_ru', models.CharField(max_length=20, null=True)),
                ('validity_en', models.CharField(max_length=20, null=True)),
                ('days', models.PositiveSmallIntegerField(help_text='Lifetime of an activation')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='packs.socialpack')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
                'unique_together': {('pack', 'slug')},
            },
        ),
    ]
