# Generated by Django 5.2.18 on 2026-10-09 12:01

from django.db import migrations, models


# Packs that already exist get their traffic here, so a database seeded before
# these fields existed works without re-seeding. Packs left out are unlimited.
INTERNET_MB = {
    "hv-20gb": 20 * 1024,
    "hv-50gb": 50 * 1024,
    "hv-100gb": 100 * 1024,
    "weekly-2gb": 2 * 1024,
    "weekly-5gb": 5 * 1024,
    "daily-500mb": 500,
    "daily-1gb": 1024,
}
SOCIAL_MB = {"1gb": 1024, "2gb": 2 * 1024, "5gb": 5 * 1024, "10gb": 10 * 1024, "100gb": 100 * 1024}
ROAMING_MB = {"r-500mb": 500, "r-2gb": 2 * 1024, "r-5gb": 5 * 1024}


def fill_amounts(apps, schema_editor):
    for model, amounts in (
        ("InternetPack", INTERNET_MB),
        ("SocialPlan", SOCIAL_MB),
        ("RoamingPack", ROAMING_MB),
    ):
        rows = apps.get_model("packs", model).objects
        for slug, data_mb in amounts.items():
            rows.filter(slug=slug).update(data_mb=data_mb)


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetpack',
            name='data_mb',
            field=models.PositiveIntegerField(blank=True, help_text='Empty = unlimited', null=True),
        ),
        migrations.AddField(
            model_name='roamingpack',
            name='data_mb',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='socialplan',
            name='data_mb',
            field=models.PositiveIntegerField(default=0, help_text='Traffic of the app it covers'),
        ),
        migrations.RunPython(fill_amounts, migrations.RunPython.noop),
    ]
