# Generated by Django 5.2.18 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_included_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetpack',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='internetpack',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='internetpack',
            name='sub_ru',
        ),
        migrations.RemoveField(
            model_name='packcategory',
            name='label_ru',
        ),
        migrations.RemoveField(
            model_name='roamingpack',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='roamingpack',
            name='sub_ru',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='cta_ru',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='periods_ru',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='subtitle_ru',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='socialpack',
            name='volume_ru',
        ),
        migrations.RemoveField(
            model_name='socialplan',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='socialplan',
            name='validity_ru',
        ),
    ]
