# Generated by Django 5.2.18 on 2026-10-09 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('name_az', models.CharField(max_length=80, null=True)),
                ('name_ru', models.CharField(max_length=80, null=True)),
                ('name_en', models.CharField(max_length=80, null=True)),
                ('sub', models.CharField(max_length=160)),
                ('sub_az', models.CharField(max_length=160, null=True)),
                ('sub_ru', models.CharField(max_length=160, null=True)),
                ('sub_en', models.CharField(max_length=160, null=True)),
                ('period', models.CharField(max_length=40)),
                ('period_az', models.CharField(max_length=40, null=True)),
                ('period_ru', models.CharField(max_length=40, null=True)),
                ('period_en', models.CharField(max_length=40, null=True)),
                ('days', models.PositiveSmallIntegerField(help_text='Days until the next payment')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('auto_renew', models.BooleanField(default=True)),
                ('sections', models.JSONField(default=list, help_text='Each item is {"text"}, {"rows": [{"label", "value"}]} or {"option"}')),
                ('sections_az', models.JSONField(default=list, help_text='Each item is {"text"}, {"rows": [{"label", "value"}]} or {"option"}', null=True)),
                ('sections_ru', models.JSONField(default=list, help_text='Each item is {"text"}, {"rows": [{"label", "value"}]} or {"option"}', null=True)),
                ('sections_en', models.JSONField(default=list, help_text='Each item is {"text"}, {"rows": [{"label", "value"}]} or {"option"}', null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', max_length=12)),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_payment_at', models.DateTimeField()),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='SimProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lte_enabled', models.BooleanField(default=True)),
                ('one_way_blocking_date', models.DateField()),
                ('deactivation_date', models.DateField()),
                ('line_status', models.CharField(choices=[('open', 'Open'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='open', max_length=10)),
                ('mobile_internet', models.BooleanField(default=True)),
                ('second_line', models.BooleanField(default=True)),
                ('forward_all', models.BooleanField(default=False)),
                ('forward_unanswered', models.BooleanField(default=False)),
                ('forward_busy', models.BooleanField(default=False)),
                ('forward_unreachable', models.BooleanField(default=False)),
                ('roaming_enabled', models.BooleanField(default=False)),
                ('roaming_changed_at', models.DateTimeField(blank=True, null=True)),
                ('sms_language', models.CharField(default='az', max_length=2)),
                ('sms_ads', models.BooleanField(default=True)),
                ('sms_campaigns', models.BooleanField(default=True)),
                ('sms_partners', models.BooleanField(default=True)),
                ('puk1', models.CharField(max_length=8)),
                ('puk2', models.CharField(max_length=8)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sim', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
