# Generated by Django 5.2.18 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simservice',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='simservice',
            name='period_ru',
        ),
        migrations.RemoveField(
            model_name='simservice',
            name='sections_ru',
        ),
        migrations.RemoveField(
            model_name='simservice',
            name='sub_ru',
        ),
    ]
