# Generated by Django 5.2.18 on 2026-10-09 12:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packs', '0002_included_amounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('segment', models.CharField(choices=[('heavy_data', 'Heavy data'), ('voice_only', 'Voice only'), ('roamer', 'Roamer'), ('balanced', 'Balanced'), ('low_usage', 'Low usage')], max_length=20)),
                ('target_kind', models.CharField(choices=[('internet_pack', 'Internet pack'), ('social_pack', 'Social pack plan'), ('roaming_pack', 'Roaming pack'), ('tariff_plan', 'Tariff plan')], max_length=20)),
                ('target_id', models.CharField(help_text='Catalogue slug; for a social pack "<pack>:<plan>"', max_length=80)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valid_days', models.PositiveSmallIntegerField(default=14)),
                ('reason', models.CharField(help_text='Shown to the subscriber with the offer', max_length=200)),
                ('reason_az', models.CharField(help_text='Shown to the subscriber with the offer', max_length=200, null=True)),
                ('reason_ru', models.CharField(help_text='Shown to the subscriber with the offer', max_length=200, null=True)),
                ('reason_en', models.CharField(help_text='Shown to the subscriber with the offer', max_length=200, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('internet_pack', 'Internet pack'), ('social_pack', 'Social pack plan'), ('roaming_pack', 'Roaming pack'), ('tariff_plan', 'Tariff plan')], max_length=20)),
                ('target_id', models.CharField(max_length=80)),
                ('normal_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.CharField(blank=True, help_text='Used when there is no rule', max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('shown', 'Shown'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('activation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer', to='packs.packactivation')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='usage.offerrule')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('heavy_data', 'Heavy data'), ('voice_only', 'Voice only'), ('roamer', 'Roamer'), ('balanced', 'Balanced'), ('low_usage', 'Low usage')], db_index=True, max_length=20)),
                ('data_mb', models.PositiveIntegerField(default=0)),
                ('minutes', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saving', models.DecimalField(decimal_places=2, default=0, help_text='Of the top recommendation, per month', max_digits=10)),
                ('recommendation', models.CharField(blank=True, max_length=160)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('app', models.CharField(max_length=30)),
                ('data_mb', models.PositiveIntegerField(default=0)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'app usage',
                'indexes': [models.Index(fields=['day', 'app'], name='usage_app_day_app')],
                'unique_together': {('subscriber', 'day', 'app')},
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('data_mb', models.PositiveIntegerField(default=0, help_text='Mobile data at home')),
                ('call_minutes', models.PositiveIntegerField(default=0)),
                ('sms', models.PositiveIntegerField(default=0)),
                ('roaming_data_mb', models.PositiveIntegerField(default=0)),
                ('roaming_minutes', models.PositiveIntegerField(default=0)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'daily usage',
                'indexes': [models.Index(fields=['day'], name='usage_daily_day')],
                'unique_together': {('subscriber', 'day')},
            },
        ),
    ]
