# Generated by Django 5.2.18 on 2026-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='overage_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What that part cost', max_digits=8),
        ),
        migrations.AddField(
            model_name='dailyusage',
            name='overage_mb',
            field=models.PositiveIntegerField(default=0, help_text='Part of the data that was outside every package'),
        ),
    ]
