# Generated by Django 5.2.18 on 2026-10-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_overage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerrule',
            name='reason_ru',
        ),
    ]
