# Generated by Django 5.2.18 on 2026-10-09 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('video_heavy', 'Video heavy'), ('repeat_packs', 'Repeat packs'), ('overage', 'Out of package'), ('forecast_gap', 'Forecast gap'), ('social_heavy', 'Social heavy'), ('underused', 'Underused'), ('roaming', 'Roaming'), ('renewal_shortfall', 'Renewal shortfall')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('urgent', 'Urgent')], default='info', max_length=10)),
                ('evidence', models.JSONField(default=dict, help_text='The figures the detector found')),
                ('offers', models.JSONField(default=list, help_text='Priced catalogue answers, best first')),
                ('recommended', models.PositiveSmallIntegerField(default=0, help_text='Index into offers')),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('expired', 'Expired'), ('resolved', 'Resolved')], default='new', max_length=10)),
                ('accepted_offer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the app was first given it', null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, help_text='No insight of this kind is written before this', null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subscriber', 'status'], name='insight_subscriber_status')],
            },
        ),
    ]
