# Generated by Django 5.2.18 on 2026-10-09 12:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('renewal_shortfall', 'Renewal shortfall'), ('overage', 'Out of data'), ('forecast_gap', 'Data will run out'), ('repeat_packs', 'Repeated packs'), ('roaming', 'Roaming'), ('social_heavy', 'Social networks'), ('underused', 'Underused data'), ('video_heavy', 'Video')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed')], default='new', max_length=10)),
                ('evidence', models.JSONField(default=dict)),
                ('offers', models.JSONField(default=list)),
                ('recommended', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subscriber', 'kind')},
            },
        ),
    ]
